services:
  jekyll:
    image: ruby:3.1
    working_dir: /srv/jekyll
    volumes:
      - .:/srv/jekyll
    command: bash -c "bundle install && bundle exec jekyll serve --livereload --force_polling --host 0.0.0.0"
    ports:
      - "4000:4000"
      - "35729:35729"
